[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/posts/*"
  to = "/.netlify/functions/api/posts/:splat"
  status = 200

[[redirects]]
  from = "/new"
  to = "/.netlify/functions/api/new"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api/"
  status = 200
